version: '3.7'

services:
  
  message-queue:
    image: dockeronwindows/ch05-nats:2e
    networks:
      - nd-net

  elasticsearch:
    image: sixeyed/elasticsearch:5.6.11-windowsservercore-ltsc2019
    environment: 
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
    volumes:
      - es-data:C:\data
    networks:
      - nd-net

  reverse-proxy:
    image: sixeyed/traefik:v1.7.8-windowsservercore-ltsc2019
    command: docker --docker.swarmMode --docker.watch --docker.endpoint=tcp://win2019-dev-02:2376 --docker.tls.ca=/certs/ca.pem --docker.tls.cert=/certs/cert.pem --docker.tls.key=/certs/key.pem
    ports:
      - "80"
      - "8080"
    networks:
      - nd-net

  docker service create `
 --detach=true `
 --network nd-swarm `
 --constraint=node.role==manager `
 --publish 80:80 --publish 8080:8080 `
 --mount type=bind,source=C:\certs\client,target=C:\certs `
 --name reverse-proxy `
 sixeyed/traefik:v1.7.8-windowsservercore-ltsc2019 `
 --docker --docker.swarmMode --docker.watch `
 --docker.endpoint=tcp://win2019-dev-02:2376 `
 --docker.tls.ca=/certs/ca.pem `
 --docker.tls.cert=/certs/cert.pem `
 --docker.tls.key=/certs/key.pem `
 --logLevel=DEBUG --api

  kibana:
    image: sixeyed/kibana:5.6.11-windowsservercore-ltsc2019
    labels:
      - "traefik.frontend.rule=Host:kibana.nerddinner.local"
    depends_on:
      - elasticsearch
    networks:
      - nd-net

  nerd-dinner-db:
    image: dockeronwindows/ch06-nerd-dinner-db:2e
    env_file:
      - db-credentials.env
    volumes:
      - db-data:C:\data
    networks:
      - nd-net

  nerd-dinner-save-handler:
    image: dockeronwindows/ch05-nerd-dinner-save-handler:2e
    depends_on:
      - nerd-dinner-db
      - message-queue
    env_file:
      - db-credentials.env
    networks:
      - nd-net

  nerd-dinner-index-handler:
    image: dockeronwindows/ch05-nerd-dinner-index-handler:2e
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - nd-net

  nerd-dinner-api:
    image: dockeronwindows/ch05-nerd-dinner-api:2e
    labels:
      - "traefik.frontend.rule=Host:api.nerddinner.local"
    env_file:
      - db-credentials.env
    depends_on:
      - nerd-dinner-db
    networks:
      - nd-net

  nerd-dinner-homepage:
    image: dockeronwindows/ch03-nerd-dinner-homepage:2e
    labels:
      - "traefik.frontend.rule=Host:nerddinner.local;Path:/,/css/site.css"
      - "traefik.frontend.priority=10"
    networks:
      - nd-net

  nerd-dinner-web:
    image: dockeronwindows/ch05-nerd-dinner-web:2e
    labels:
      - "traefik.frontend.rule=Host:nerddinner.local;PathPrefix:/"
      - "traefik.frontend.priority=1"
      - "traefik.backend.loadbalancer.stickiness=true"
    environment: 
      - HomePage:Enabled=false
      - DinnerApi:Enabled=true
    env_file:
      - api-keys.env
      - db-credentials.env
    depends_on:
      - nerd-dinner-db
      - message-queue
    networks:
      - nd-net

networks:
  nd-net:
    external:
      name: nat

volumes:
  es-data:
  db-data: