version: '3.7'

services:
  
  reverse-proxy:
    command: --docker --docker.swarmMode --docker.watch --docker.endpoint=tcp://10.0.0.5:2375 --api   

  kibana:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:kibana.nerddinner.sixeyed.com"
        - "traefik.port=5601"

  nerd-dinner-api:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:api.nerddinner.sixeyed.com"
        - "traefik.port=80"

  nerd-dinner-homepage:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:nerddinner.sixeyed.com;Path:/,/css/site.css"
        - "traefik.frontend.priority=10"
        - "traefik.port=80"

  nerd-dinner-web:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:nerddinner.sixeyed.com;PathPrefix:/"
        - "traefik.frontend.priority=1"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.port=80"